### ISSUE TITLE
Doesn't work with RS256

### ISSUE THREAD

**Issue by chalcedonyt** [lombax85/nginx-jwt#3]
The `crypto.createVerify` method is not available in njs (http://nginx.org/en/docs/njs/reference.html#crypto). Unfortunately this doesn't look fixable

**Comment by jobmission** [comment]
Is there any solution?

**Comment by jobmission** [comment]
@chalcedonyt solved?

**Comment by lombax85** [comment]
I did’t have a chance to verify this, sorry. If someone has a fix feel free to make a PR

**Comment by Sarniak1991** [comment]
@chalcedonyt Confirm
TypeError: (intermediate value)["createVerify"] is not a function

**Comment by chalcedonyt** [comment]
@jobmission @Sarniak1991 unfortunately I don't think this is fixable, it's not a problem with this library but with njs. The functions needed for RS256 are not available in the Nginx flavour of JS (as reflected in http://nginx.org/en/docs/njs/reference.html#crypto)
